This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./Abschlussarbeit.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Abschlussarbeit.acn....done (11 entries accepted, 0 rejected).
Sorting entries....done (41 comparisons).
Generating output file Abschlussarbeit.acr....done (35 lines written, 0 warnings).
Output written in Abschlussarbeit.acr.
Transcript written in Abschlussarbeit.alg.
